# Generated by Django 2.1.5 on 2019-01-26 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed', models.BooleanField(default=False)),
                ('itemCount', models.IntegerField()),
                ('itemDesc', models.CharField(max_length=100)),
                ('basketPic', models.ImageField(upload_to='basketpics')),
            ],
            options={
                'db_table': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('profilePic', models.ImageField(upload_to='userdps')),
            ],
            options={
                'db_table': 'civilians',
            },
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('orgLogo', models.ImageField(upload_to='ngologos')),
                ('certificate', models.ImageField(upload_to='ngocerts')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'ngos',
            },
        ),
        migrations.AddField(
            model_name='basket',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.NGO'),
        ),
        migrations.AddField(
            model_name='basket',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Civilian'),
        ),
    ]
