# Generated by Django 2.1.5 on 2019-01-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='darpanId',
            field=models.CharField(default='', max_length=30),
        ),
    ]
